version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskDefinitionARN:tag"
        LoadBalancerInfo:
          ContainerName: "container-name"
          ContainerPort: 5000
